server:
  port: 8080
springdoc:
  swagger-ui:
    path: "/doc/swagger-ui/index.html"
  api-docs:
    path: "/doc/api-docs"
spring:
  webflux:
    base-path: "/api"
  application:
    name: dynamo-rabbit-challenge
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
logging:
  level:
    com.ias.microserviceusers: DEBUG
    org.slf4j: DEBUG

aws:
  dynamodb:
    endpoint: "http://localhost:8010"
  region: "us-east-1"